#!/bin/bash
/home/wwillett/repos/bash_scripts/compare_group_membership srv-02-1103 srv-02-1105	epicsys
echo ""
echo "-----------"
echo ""
/home/wwillett/repos/bash_scripts/compare_group_membership srv-02-1103 srv-02-1105	epicuser
echo ""
echo "-----------"
echo ""
/home/wwillett/repos/bash_scripts/compare_group_membership srv-02-1103 srv-02-1105	cachegrp
echo ""
echo "-----------"
echo ""
/home/wwillett/repos/bash_scripts/compare_group_membership srv-02-1103 srv-02-1105	dmngrp
echo ""
echo "-----------"
echo ""
/home/wwillett/repos/bash_scripts/compare_group_membership srv-02-1103 srv-02-1105	iscagent
echo ""
echo "-----------"
echo ""
/home/wwillett/repos/bash_scripts/compare_group_membership srv-02-1103 srv-02-1105	epicis
echo ""
echo "-----------"
echo ""
/home/wwillett/repos/bash_scripts/compare_group_membership srv-02-1103 srv-02-1105	epicts
echo ""
echo "-----------"
echo ""
/home/wwillett/repos/bash_scripts/compare_group_membership srv-02-1103 srv-02-1105	epicssts
echo ""
echo "-----------"
echo ""
/home/wwillett/repos/bash_scripts/compare_group_membership srv-02-1103 srv-02-1105	ifhsupt
echo ""
echo "-----------"
echo ""
/home/wwillett/repos/bash_scripts/compare_group_membership srv-02-1103 srv-02-1105	analyst
echo ""
echo "-----------"
echo ""
/home/wwillett/repos/bash_scripts/compare_group_membership srv-02-1103 srv-02-1105	programmer
echo ""
echo "-----------"
echo ""
/home/wwillett/repos/bash_scripts/compare_group_membership srv-02-1103 srv-02-1105	helpdesk
echo ""
echo "-----------"
echo ""
/home/wwillett/repos/bash_scripts/compare_group_membership srv-02-1103 srv-02-1105	linuxadmins
echo ""
echo "-----------"
echo ""
/home/wwillett/repos/bash_scripts/compare_group_membership srv-02-1103 srv-02-1105	odbadmins
echo ""
echo "-----------"
echo ""
/home/wwillett/repos/bash_scripts/compare_group_membership srv-02-1103 srv-02-1105	allow_shell
echo ""
echo "-----------"
echo ""
/home/wwillett/repos/bash_scripts/compare_group_membership srv-02-1103 srv-02-1105	irisusr
echo ""
echo "-----------"
echo ""
/home/wwillett/repos/bash_scripts/compare_group_membership srv-02-1103 srv-02-1105	dbarpt
echo ""
echo "-----------"
echo ""
/home/wwillett/repos/bash_scripts/compare_group_membership srv-02-1103 srv-02-1105	reporting
echo ""
echo "-----------"
echo ""
/home/wwillett/repos/bash_scripts/compare_group_membership srv-02-1103 srv-02-1105	interfaces
